version: '3.8'

networks:
  nodejs2024q1-service:
    driver: bridge

services:
  db:
    container_name: nodejs2024q1-service-app-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    build: ./database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/data/:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - nodejs2024q1-service
  app:
    container_name: nodejs2024q1-service-app
    platform: linux/amd64 #for platform error on Apple M1 chips
    build: .
    command: npm run start:dev
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./src/:/app/src/
    ports:
      - ${PORT}:${PORT}
    networks:
      - nodejs2024q1-service
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-nodejs2024q1-service-app-db}


